spring: 
  profiles: 
   active: prod
  
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/apidatabase?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8 
    username: root 
    password: W@ng0811 
  
  jpa: 
    hibernate: 
      ddl-auto: update 
    show-sql: true
